package model

import androidx.room.Entity
import androidx.room.PrimaryKey

// Declares this class as a Room entity representing a table named "distractions"
@Entity(tableName = "distractions")
data class Distraction(
    // Unique ID for each distraction, auto-generated by Room
    @PrimaryKey(autoGenerate = true) val id: Int = 0,

    // Type of distraction: e.g., "joke", "quote", or "fact"
    val type: String,

    // The actual content (text) of the distraction
    val content: String
)
